version: '3'

services:
  telegram_bot:
   build: 
     context: "./bot"
   volumes:
     - ./screenshot_bot/:/screenshot_bot
   container_name: "telegram_bot"
   env_file:
     - ./.env
   command: python3 screenshots_bot.py
     
  redis:
    image: redis
    restart: always
    container_name: "redis_bot"
    command: redis-server
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./celery
    volumes: 
      - ./screenshot_bot/:/screenshot_bot
    depends_on:
      - redis
      - telegram_bot
    container_name: "celery_bot"
    env_file:
      - ./.env
    command: celery -A celery_screenshot_tasks worker -c 1 --loglevel=INFO
